Repository puppetlabs/pdk-templates, pull requests merged in 2018-06, with the labels that each got.

#79 (PDK-681) Remove puppet-blacksmith
  config_defaults.yml
Labels: enhancement

#106 (PDK-903) ignore `.git` directory
  config_defaults.yml
Labels: bug

#103 revise Style/Documentation excludes
  config_defaults.yml
Labels: bug

#93 Make gitlab cache configurable
  README.md
  config_defaults.yml
  moduleroot/.gitlab-ci.yml.erb
Labels: gitlab

#110 (feature) Allow code coverage in .travis.yml
  README.md
  moduleroot/.travis.yml.erb
  moduleroot/Rakefile.erb
Labels: enhancement

#111 (feature) add github changelog generator template
  README.md
  moduleroot/Rakefile.erb
Labels: enhancement
