Repository puppetlabs/pdk-templates, pull requests merged in 2020-12, with the labels that each got.

#368 (maint) Update Ruby version for Appveyor linting checks
  config_defaults.yml
Labels: maintenance

#370 (SEC-250) Pin non-github provided actions to a specific SHA
  moduleroot/.github/workflows/nightly.yml.erb
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: Ticketed - JIRA, bug

#371 Updates for ruby 2.4 and rubocop 1.6.1
  .travis/install_pdk.sh
  Gemfile
  config_defaults.yml
  moduleroot/.rubocop.yml.erb
  moduleroot/.travis.yml.erb
  rubocop/cleanup_cops.yml
  rubocop/defaults-1.6.1.yml
  rubocop/profile_builder.rb
Labels: enhancement

#374 Fix Include syntax for new rubocop
  moduleroot/.rubocop.yml.erb
  object_templates/provider_type.erb
Labels: bug

#375 Remove Layout/HashAlignment from the default cleanup cops
  config_defaults.yml
  rubocop/cleanup_cops.yml
Labels: enhancement

#376 (IAC-1026) - Removal of Inappropriate Terminology
  .travis/test_script.sh
  README.md
Labels: maintenance
