Repository puppetlabs/pdk-templates, pull requests merged in 2020-11, with the labels that each got.

#332 Add global_variables key for GitLab CI to set defaults that can be overridden by jobs
  moduleroot/.gitlab-ci.yml.erb
Labels: enhancement, gitlab

#354 Add gitpod support for puppet modules
  README.md
  config_defaults.yml
  moduleroot/.gitpod.Dockerfile
  moduleroot/.gitpod.yml
Labels: enhancement

#364 Avoid second failure if provision doesn't create inventory
  moduleroot/.github/workflows/nightly.yml.erb
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: bug

#365 Update honeycomb buildevents tracking
  moduleroot/.github/workflows/nightly.yml.erb
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: enhancement

#367 github actions: Don't retry at the workflow level
  moduleroot/.github/workflows/nightly.yml.erb
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: bug

#366 Allow to use a different dist per collection
  moduleroot/.travis.yml.erb
Labels: enhancement

#360 (fix) Set rubocop ruby version to 2.4
  moduleroot/.rubocop.yml.erb
Labels: bug
