Repository puppetlabs/pdk-templates, pull requests merged in 2021-01, with the labels that each got.

#384 Remove obsolete beaker instructions
  README.md
Labels: maintenance

#383 Fix handling of `pending` cops; configure some egregious cops
  config_defaults.yml
  moduleroot/.rubocop.yml.erb
  rubocop/defaults-1.6.1.yml
  rubocop/profile_builder.rb
Labels: enhancement

#377 Update how we handle at-risk action sources
  README.md
  moduleroot/.github/workflows/nightly.yml.erb
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: enhancement

#378 (maint) Fix GitHub acceptance test setup when not common owner
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: bug

#389 (FIX) Ensure system PMG gem installed when PUPPET_GEM_VERSION nil
  config_defaults.yml
Labels: bug

#387 Allow passing even if tear-down fails in Github Action CI
  moduleroot/.github/workflows/nightly.yml.erb
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: maintenance

#382 Use ruby/setup-ruby Github action
  moduleroot/.github/workflows/nightly.yml.erb
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: enhancement

#390 Add bundler require to Rakefile
  moduleroot/Rakefile.erb
Labels: bug

#392 Revert litmus protection
  config_defaults.yml
  moduleroot/Gemfile.erb
Labels: blocked, bug
