Repository puppetlabs/pdk-templates, pull requests merged in 2021-03, with the labels that each got.

#408 Add manual module publish and tag workflow using FORGE_API_KEY secret
  moduleroot/.github/workflows/release.yml.erb
Labels: enhancement

#372 (IAC-1307) Add Spec tests to nightly and pr_test GHActions configs
  moduleroot/.github/workflows/spec.yml.erb
Labels: enhancement

#415 Use puppet/iac_release:ci image for auto release prep
  moduleroot/.github/workflows/auto_release.yml.erb
Labels: maintenance

#414 (GH-380) Relocation of inventory.yaml file
  moduleroot/.github/workflows/nightly.yml.erb
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: enhancement

#417 Add static & syntax checks to spec workflow
  config_defaults.yml
  moduleroot/.github/workflows/spec.yml.erb
Labels: bug

#421 (GH-419) Removal of win32 gems
  moduleroot/Gemfile.erb
Labels: enhancement, maintenance
