Repository puppetlabs/pdk-templates, pull requests merged in 2021-02, with the labels that each got.

#393 Add automatic release preparation workflow
  moduleroot/.github/workflows/auto_release.yml.erb
Labels: enhancement

#338 Gitlab litmus
  README.md
  config_defaults.yml
  moduleroot/.gitlab-ci.yml.erb
Labels: enhancement, gitlab

#395 Finalise auto-release-prep using pdk-docker image and cleanup artifacts
  moduleroot/.github/workflows/auto_release.yml.erb
Labels: enhancement

#399 Make litmus[variables] optional
  moduleroot/.gitlab-ci.yml.erb
Labels: bug, gitlab

#401 (#397) Address some validation issues in object_templates
  .travis/test_script.sh
  config_defaults.yml
  object_templates/fact.erb
  object_templates/fact_spec.erb
  object_templates/functions/function_spec.erb
  object_templates/functions/native_function.erb
  object_templates/functions/v4_function.erb
  object_templates/transport_device.erb
Labels: bug

#402 Don't enforce frozen string comments
  config_defaults.yml
Labels: enhancement

#403 Remove puppet5 from config_defaults.yml
  config_defaults.yml
Labels: enhancement

#405 Re-add ClassAndModuleCamelCase disabling on transport_device
  .travis/test_script.sh
  object_templates/transport_device.erb
Labels: bug

#404 Use rspec-mocks as default mocking library
  README.md
  config_defaults.yml
Labels: enhancement

#409 (maint) Updating version and owner in release workflow
  moduleroot/.github/workflows/auto_release.yml.erb
Labels: maintenance

#410 Add commit reference in PR body on auto release prep
  moduleroot/.github/workflows/auto_release.yml.erb
Labels: maintenance

#398 Use different providers in Github Action workflows matrix
  moduleroot/.github/workflows/nightly.yml.erb
  moduleroot/.github/workflows/pr_test.yml.erb
Labels: enhancement
