Repository puppetlabs/pdk-templates, pull requests merged in 2021-05, with the labels that each got.

#432 Fix Bug in .rubocop.yml.erb
  moduleroot/.rubocop.yml.erb
Labels: bug

#431 Cleanup backtrace in spec tests
  moduleroot/spec/spec_helper.rb.erb
Labels: enhancement

#437 (maint) Use docker pdk:nightly container
  moduleroot/.github/workflows/release.yml.erb
Labels: maintenance

#433 Add changelog_max_issues configuration
  README.md
  moduleroot/Rakefile.erb
Labels: enhancement

#434 added tags to .gitlab-ci.yml.erb
  README.md
  moduleroot/.gitlab-ci.yml.erb
Labels: enhancement

#436 added more fine-grained control of custom_before_steps
  README.md
  moduleroot/.gitlab-ci.yml.erb
Labels: enhancement

#438 Allow auto_release workflow schedule configuration
  README.md
  moduleroot/.github/workflows/auto_release.yml.erb
Labels: enhancement
