Repository puppetlabs/pdk-templates, pull requests merged in 2023-11, with the labels that each got.

#515 Allow puppet-lint fail_on_warnings to be disabled
  moduleroot/Rakefile.erb
Labels: feature

#538 [CAT-1541] : Adding github directory to pdkignore
  config_defaults.yml
Labels: maintenance

#540 (CAT-1606) - Adding gem group for release_pre
  config_defaults.yml
Labels: enhancement

#541 (MAINT) - Updating puppetlabs_spec_helper gem version to latest
  config_defaults.yml
Labels: maintenance
