Repository puppetlabs/pdk-templates, pull requests merged in 2023-04, with the labels that each got.

#510 (CONT-885) pdk-templates v3 prep
  Gemfile
  README.md
  config_defaults.yml
  moduleroot/.devcontainer/Dockerfile
  moduleroot/.devcontainer/README.md
  moduleroot/.devcontainer/devcontainer.json
  moduleroot/.editorconfig.erb
  moduleroot/.gitlab-ci.yml.erb
  moduleroot/.gitpod.Dockerfile
  moduleroot/.gitpod.yml
  moduleroot/.rubocop.yml.erb
  moduleroot/.travis.yml.erb
  moduleroot/Rakefile.erb
  moduleroot/appveyor.yml.erb
  object_templates/functions/native_function.erb
  object_templates/transport.erb
  object_templates/transport_device.erb
  rubocop/defaults-1.48.1.yml
  rubocop/defaults-1.6.1.yml
  rubocop/profile_builder.rb
Labels: backwards-incompatible

#512 (MAINT) Fix YAML.safe_load
  moduleroot/spec/spec_helper.rb.erb
Labels: bug

#465 Enable puppet coverage reports
  config_defaults.yml
Labels: community
