Repository puppetlabs/pdk-templates, pull requests merged in 2024-01, with the labels that each got.

#539 Add documentation for manage_execute_permissions setting
  README.md
Labels: maintenance, community

#548 Remove whitespace
  moduleroot/.github/workflows/release.yml.erb
Labels: maintenance

#549 (CAT-1684) Addition of CHANGELOG.md
  .github/workflows/release_prep.yml
Labels: maintenance

#550 (CAT1684) Add blank CHANGELOG.md
  CHANGELOG.md
Labels: maintenance

#552 (CAT-1684) Re-add section to workflow
  .github/workflows/release_prep.yml
Labels: maintenance

#553 (CAT-1686) Upgrade Rubocop 1.48.1 to 1.50.0
  Gemfile
  config_defaults.yml
  moduleroot/.rubocop.yml.erb
  rubocop/defaults-1.50.0.yml
Labels: maintenance

#554 (BUGFIX) Enable NewCops by default
  moduleroot/.rubocop.yml.erb
Labels: enhancement

#555 (CAT-1688) - Pin rubocop to `~> 1.50.0`
  Gemfile
  config_defaults.yml
Labels: bugfix

#556 (CAT-1693) - Remove deprecated codecov gem
  config_defaults.yml
Labels: bugfix

#545 metadata-json-lint: Switch to 4.x
  config_defaults.yml
Labels: community, bugfix
