Repository puppetlabs/pdk-templates, pull requests merged in 2024-05, with the labels that each got.

#575 (MAIT) Readme syntax fixes
  README.md
Labels: maintenance

#576 facterdb: Require 1.26 or newer
  config_defaults.yml
Labels: maintenance, community

#580 (IT-87329) - Update workflows to run on pull_request
  .github/workflows/mend.yml
Labels: maintenance

#565 Add bolt-related files to .gitignore default paths
  config_defaults.yml
Labels: community

#582 (CAT-1871) Pin `rexml` due to issues on Windows
  config_defaults.yml
Labels: bugfix
